import { cache } from "react";

import { D2C } from "@/lib/partner";

/**
 * What i2b actually stocks, read live.
 *
 * ## Why this is not a generated map
 *
 * There was one: `handoff-map.ts`, generated by matching ReViaLife's sitemap
 * against i2b's catalogue and committed. Between the day it was written and the
 * day this replaced it, it had already rotted — 86 slugs became 84, 19
 * destinations became 18, and `acetic-acid-water` went from a working link to a
 * 404 because the product was deactivated on i2b. Nothing announced any of it.
 * The link still looked right.
 *
 * The owner's ruling makes that failure certain rather than merely likely: the
 * compounds i2b does not stock sit in its admin as hidden rows, to be switched
 * on one at a time whenever he decides to carry one. A map regenerated by a
 * deploy cannot track a decision made in an admin panel. So this reads the
 * catalogue at render time, and a compound gains its link within the ISR window
 * of being activated, with no deploy and nobody remembering to run a script.
 *
 * ## Why i2b's own endpoint is the right source
 *
 * `/api/catalogue` on i2b already answers exactly this question and no more: it
 * returns `active: true` products only, and it carries **no prices** by explicit
 * design — its own comment calls pricing on a property you do not control a
 * pricing leak. That matters here beyond convenience. ReViaLife must not publish
 * a price, and the safest way to honour that is to consume a feed that cannot
 * supply one.
 *
 * It sets no CORS headers, also deliberately, so it can only be read
 * server-to-server. Everything here is server-side for that reason.
 *
 * ## null is not []
 *
 * A failed fetch returns `null`; a reachable catalogue with no matches returns
 * an array. The distinction is the whole safety property: "i2b does not stock
 * this" is a claim, and it cannot be made on the strength of a request that
 * never arrived. `src/lib/stats.ts` draws the same line for the same reason —
 * a number that could not be read is never rendered as zero.
 */

/** One product as i2b publishes it. Never a price — see above. */
export interface I2bProduct {
  slug: string;
  name: string;
  description: string | null;
  category: string | null;
  image: string | null;
  coaUrl: string | null;
  /** Sizes as printed on the label — "5mg", "10mg". */
  sizes: string[];
  inStock: boolean;
}

/**
 * How long a catalogue read is reused. Fifteen minutes is the lag between the
 * owner activating a product and its link appearing here — short enough that he
 * can check his work in one sitting, long enough that ReViaLife is not a load
 * generator against i2b.
 */
const REVALIDATE_SECONDS = 900;

/**
 * A slow catalogue must not become a slow page. Three seconds is well past a
 * healthy response and well short of anything a reader would wait through; past
 * it, the control simply does not render.
 */
const TIMEOUT_MS = 3000;

/**
 * The live catalogue, or null if it could not be read.
 *
 * Never throws. A page that renders a compound monograph must not 500 because a
 * sibling site is down — the monograph is the point, the buy control is not.
 *
 * `cache` dedupes within a single render, so a page mounting the control twice
 * makes one request.
 */
export const getI2bCatalogue = cache(async (): Promise<I2bProduct[] | null> => {
  if (!D2C.origin) return null;

  try {
    const res = await fetch(`${D2C.origin}/api/catalogue`, {
      next: { revalidate: REVALIDATE_SECONDS, tags: ["i2b-catalogue"] },
      signal: AbortSignal.timeout(TIMEOUT_MS),
      headers: { accept: "application/json" },
    });
    if (!res.ok) return null;

    // The endpoint answers `{ count, items }`. A bare array is accepted too, so
    // a future change of envelope degrades to "unavailable" rather than to a
    // silently empty catalogue — which would read as "i2b stocks nothing".
    const body: unknown = await res.json();
    const items = Array.isArray(body)
      ? body
      : Array.isArray((body as { items?: unknown }).items)
        ? (body as { items: unknown[] }).items
        : null;
    if (!items) return null;

    // Shape-check rather than trust. A catalogue that changes shape should read
    // as unavailable, not as an empty catalogue — the same reason null and []
    // are kept apart above.
    const parsed = items.filter(
      (i): i is I2bProduct =>
        typeof i === "object" &&
        i !== null &&
        typeof (i as I2bProduct).slug === "string" &&
        typeof (i as I2bProduct).name === "string",
    );
    return parsed.length > 0 ? parsed : null;
  } catch {
    return null;
  }
});
